version: '3.5'
services:
  nginx:
    env_file:
      - .env
    image: mobidevpublisher/nginx:stable
    restart: on-failure
    environment:
      NGINX_PREDEFINED_TEMPLATE: 'laravel.conf.template'
      NGINX_SERVER_NAME: 'localhost'
      NGINX_PORT: 8080
      NGINX_ROOT: /var/www/app/public
      PHP_HOST: php
      PHP_PORT: 9000
    working_dir: /var/www/app/
    volumes:
      - '.:/var/www/app/'
    networks:
      - local
    depends_on:
      - php
    ports:
      - '8080:8080'
    expose:
      - '8080'

  php:
    env_file:
      - .env
    working_dir: /var/www/app/
    image: mobidevpublisher/php:8.0
    restart: on-failure
    environment:
      PHP_ENABLED_EXTENSIONS: 'amqp apcu sodium redis zip pdo_pgsql gd gmp mysqli'
      PHP_ALLOW_URL_FOPEN: 'On'
      PHP_MAX_EXECUTION_TIME: 60
      PHP_MAX_INPUT_TIME: 60
      PHP_MEMORY_LIMIT: '128M'
      PHP_POST_MAX_SIZE: '120M'
      PHP_UPLOAD_MAX_FILESIZE: '100M'
      PHP_SHORT_OPEN_TAG: 'On'
      PHP_DISPLAY_ERRORS: 'On'
      PHP_DISPLAY_STARTUP_ERRORS: 'On'
    volumes:
      - '.:/var/www/app/'
    networks:
      - local

  db:
    image: mysql:latest 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: yana
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    ports:
      - '3306:3306'
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    networks:
      - local

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - '8081:80'
    networks:
      - local

networks:
  local:
    name: local

volumes:
  dbdata:
    driver: local